### ISSUE TITLE
Create API for retrieving card data. 

### ISSUE THREAD

**Issue by danclay91** [pmock2/CritWin#3]
A rest API that can be used to retrieve card data. This data should be in JSON format. This API will be used by website and future mobile application.

**Comment by danclay91** [comment]
Closing this issue. Currently you can retrieve an array containing JSON representations of all user cards by making a request to: http://critwin.com/test2/loginforms/cardapi.php?u=[username]. In the future, I believe it would be best to refactor and have all API in a separate directory so that the request would be sent to: http://critwin.com/api/cardapi.php?u=${username}

**Comment by pmock2** [comment]
I agree on the api directory. This would allow all of our various APIs for different tools to be handled by one file, rather than do a file for every tool.
